language: node_js
node_js:
  - 8
services:
  - docker
jobs:
  include:
    - stage: test
      before_install: cd $TRAVIS_BUILD_DIR/client
      install:
        - npm install
      script: 
        - npm run lint
        - npm test
    - stage: test
      before_install: cd $TRAVIS_BUILD_DIR/server
      install:
        - npm install
      script: 
        - npm run lint
        - npm test
    - stage: build
      script: if [ -n "$TRAVIS_TAG" ]; then
                docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
                docker build -t $DOCKER_REPO:$TRAVIS_COMMIT .;
                docker tag $DOCKER_REPO:$TRAVIS_COMMIT $DOCKER_REPO:$TRAVIS_TAG;
                docker tag $DOCKER_REPO:$TRAVIS_COMMIT $DOCKER_REPO:latest;
                docker push $DOCKER_REPO;
              fi
stages:
  - test
  - build
